# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-06-22 15:41
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='mapmusic',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('musicname', models.CharField(max_length=30)),
                ('lat', models.CharField(max_length=30)),
                ('lng', models.CharField(max_length=30)),
                ('uploaderemail', models.EmailField(max_length=254)),
                ('uploadtime', models.DateTimeField(auto_now_add=True)),
                ('text', models.TextField()),
                ('display', models.BooleanField(default=True)),
                ('reviewtext', models.TextField()),
                ('musicfile', models.FileField(upload_to='')),
            ],
        ),
    ]
