# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-05-03 18:27
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_mapmusic_display'),
    ]

    operations = [
        migrations.RenameField(
            model_name='mapmusic',
            old_name='uploadetime',
            new_name='uploadtime',
        ),
        migrations.AddField(
            model_name='mapmusic',
            name='reviewtext',
            field=models.TextField(default=''),
            preserve_default=False,
        ),
    ]
